### ISSUE TITLE
List dns entries in RubyDNS

### ISSUE THREAD

**Issue by bertramn** [BerlinVagrant/vagrant-dns#56]
After landrush is dead and buried, I am looking for a new dns solution.

Is it possible for this plugin to somehow list the DNS entries in the RubDNS? Also where are these records stored, are they just held in memory or written to disk to survive restarts? Last but not least,  I noticed that the DNS server is restarted every time I do a `vagrant reload`, if I run a vagrant file with multiple machines will any old configuration be flushed?

**Comment by fnordfish** [comment]
Hi @bertramn 

general design goals are described in (the quite old) [PLATFORM_SUPPORT.md](https://github.com/BerlinVagrant/vagrant-dns/blob/master/PLATFORM_SUPPORT.md).

> Is it possible for this plugin to somehow list the DNS entries in the RubDNS?

There is no build-in command for doing so. But: see next point (Issue/PR welcome :))

>  Also where are these records stored, are they just held in memory or written to disk to survive restarts?

Configured dns patterns are stored in `~/.vagrant.d/tmp/dns/config`. It's basically a big list of regex-patterns mapping IPs (like this: `"^(.*.)?foobar.test$": 33.33.0.11`)
This file gets updated (new records added) during the start of a box. That's why the dns server gets restarted. This file is not cleared up automatically. 

> ... if I run a vagrant file with multiple machines will any old configuration be flushed?

No. (see above)

**Comment by bertramn** [comment]
thanks @fnordfish, took the plugin through the paces and looks like its up to the job of replacing landrush. Having a command like `vagrant dns --list` to list out the patterns of the config file would be a nice enhancement. The other thing that could be improved is when a VM is destroyed, any pattern it registered could be cleaned up in the config file and the dns service reloaded. This way we'd never have to hack the config file directly. Great job :)

**Comment by fnordfish** [comment]
Right. Would you mind creating two separate issues?

Regarding the cleanup: removing configured patterns should be doable, but not detecting changes (editing the Vagrantfile). I think, that’s why most ppl just trash the entire config and let it auto-generate with the next start

**Comment by fnordfish** [comment]
released as [v2.1.0](https://github.com/BerlinVagrant/vagrant-dns/blob/master/CHANGELOG.md#210)
